### ISSUE TITLE
Autoplay disables controls

### ISSUE THREAD

**Issue by wolfgang-stark** [jonnitto/Jonnitto.PrettyEmbedVideo#3]
**Describe the bug**
Controls work just fine except autoplay is active.
Is this a bug or a feature?

**To Reproduce**

1. Add a node with an internal video
2. Enable controls and autoplay

**Expected behavior**
Video should autoplay and controls should be visible, at least when hovering.

**Desktop:**

- OS: Windows & Mac
- Browser: Chrome, Safari

**Additional context**

The behavior is caused by this style definition:

```scss
.jonnitto-prettyembed--video {
...
  &.jonnitto-prettyembed--autoplay {
    pointer-events: none;
  }
...
}
```
